name: Dataflow CI

on:
  push:
    paths:
      - 'src/**'
    branches:
      - master
env:
  main_class: com.commercetools.LogIngestion
  output_table_spec: some
  gcp_temp_location: some
  runner: DataflowRunner
  region: some
  input_subscription: some
  gcs_bucket_name: some

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          mvn -Pdataflow-runner compile exec:java -Dexec.mainClass=$main_class \
          -Dexec.args="--outputTableSpec=$output_table_spec \
          --gcpTempLocation=$gcp_temp_location \
          --inputSubscription=$input_subscription \
          --GcsBucketName=$gcs_bucket_name
          --runner=$runner \
          --region=$region"